# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: 'macOS-10.15'

variables:
  AWS_ACCESS_KEY_ID: $(AWS.AccessKeyID)
  AWS_SECRET_ACCESS_KEY: $(AWS.SecretAccessKey)
  SLACK_API_TOKEN: $(Slack.API_TOKEN)

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleDebug test'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true

- task: CopyFiles@2
  inputs:
    Contents: '**/*.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish artifacts

- task: S3Upload@1
  inputs:
    regionName: 'ap-northeast-1'
    bucketName: 's3-tokyo-dev.rememberapp.co.kr'
    sourceFolder: '$(build.artifactStagingDirectory)'
    globExpressions: '**/*.apk'
    targetFolder: 'android/apk/$(Build.BuildNumber)'
    filesAcl: 'public-read-write'
    createBucket: true

- task: SlackNotification@5
  inputs:
    SlackApiToken: '$(Slack.API_TOKEN)'
    MessageAuthor: 'Azure DevOps'
    Channel: '#android_ci_test'
    NotificationType: 'ChatMessage'
    Message: 'Hello World!'